### ISSUE TITLE
Non standard characters problem

### ISSUE THREAD

**Issue by TristonStuart** [nhooyr/rankbot#11]
The guild i was trying to rank up in had non standard characters and would not work properly.

To fix this i changed the code to log the servers and got the correct characters to work.
Maybe add a feature to log the guilds available automatically?

Thanks :) love the bot otherwise

**Comment by nhooyr** [comment]
Glad you enjoy it :)

What do you mean by log the servers/guilds?

**Comment by nhooyr** [comment]
Ah ok I see what you mean. Wouldn't it be easier to just copy the guild name from the discord?

**Comment by nhooyr** [comment]
Closing due to lack of response.
