### ISSUE TITLE
CAPTCHA problem

### ISSUE THREAD

**Issue by GingerMinute** [nhooyr/rankbot#15]
Hey there, I got the bot to work as intended for a while, but when coming back to it, it keeps giving me the error: `Unable to fetch discord authentication token. HTTP 400 Bad Request, {"captcha_key": ["captcha-required"]}`
Is there a solution you know to this?

**Comment by bill1on** [comment]
![image](https://user-images.githubusercontent.com/31374119/41751527-77cb1a32-75ca-11e8-9d28-27b2c22f9fd9.png)

same issue here, this recently started happening (it was all alright 2 days ago)

**Comment by GingerMinute** [comment]
Tried to do it on another account, same problem.

**Comment by bill1on** [comment]
Seems to be fixed for me by it self, don't know if it will start happening again or not but for now it's working.

**Comment by GingerMinute** [comment]
Yeah, fixed itself for me too.

**Comment by dariotrombello** [comment]
I have this issue too
