### ISSUE TITLE
cannot use g (type *discordgo.UserGuild) as type *discordgo.Guild in return argument

### ISSUE THREAD

**Issue by nnoc** [nhooyr/rankbot#4]
Hey
Simply running the go get github or building the main.go project outputs me this error.
Is it something on my end or is the code outdated?

```
C:\Go>go get github.com/nhooyr/rankbot
# github.com/nhooyr/rankbot
projects\src\github.com\nhooyr\rankbot\main.go:58: cannot use g (type *discordgo.UserGuild) as type *discordgo.Guild in return argument

```

**Comment by nhooyr** [comment]
Code is outdated :(

I can't fix it right now because my laptop isn't working correctly. Though the fix is very simple. Where ever in the program it says `*discordgo.Guild`, replace with `*discordgo.UserGuild`.

**Comment by nnoc** [comment]
That fixed it. Running flawless. I still haven't figured out how to push code into github, which I will learn and commit this :)
Thanks for the amazing fast reply!
