### ISSUE TITLE
could not find channel

### ISSUE THREAD

**Issue by kdormer** [nhooyr/rankbot#8]
Doesn't find any channels (Sorry to keep bothering you, if this is my own error)
```
logged in
got guilds
found guild
got channels
could not find channel
exit status 1
```

**Comment by nhooyr** [comment]
What is the command you used?

**Comment by kdormer** [comment]
This is the command bar my details
```
-guild="卐Random卐Bullshittery卐" chan="muted"
```

**Comment by kdormer** [comment]
go run main.go -email="emailhere" -pass="passhere" -guild="卐Random卐Bullshittery卐" chan="muted"

**Comment by nhooyr** [comment]
Are you sure the channel is called `muted`?

**Comment by kdormer** [comment]
Positive. Tried with omission of hash tag and without

**Comment by nhooyr** [comment]
I just tested the bot on my own server and it works fine, you are definitely using the wrong channel name. Try and copy and paste it directly.

**Comment by kdormer** [comment]
Okay, will do. Thank you for your time :)
