### ISSUE TITLE
Guild issue

### ISSUE THREAD

**Issue by KikoPlayZ** [nhooyr/rankbot#9]
Good Night, I am trying to use your project, and I made it work in a discord server with all the name together, but in a discord server with separate words like this example: 'Eurovision Discord <3' doesn't work, how I make this work in -guild?

**Comment by nhooyr** [comment]
use quotes, e.g. `rankbot -guild "Eurovision Discord <3"`

**Comment by KikoPlayZ** [comment]
Still not working =/  - Still giving the same error : https://image.prntscr.com/image/R6jzyvUHQZat6YwV9R5OGQ.png

**Comment by nhooyr** [comment]
What does the error say? I can't read it.

**Comment by KikoPlayZ** [comment]
System couldn't find the specified file

**Comment by nhooyr** [comment]
Must be something specific to the windows command line.

Google "how to send an argument with spaces in cmd.exe" and you'll likely find the answer.

**Comment by nhooyr** [comment]
Oh sorry, didn't specify but I think its misinterpreting the double quotes as a file read.

**Comment by KikoPlayZ** [comment]
Tried with the 2 quotes but still persists. https://image.prntscr.com/image/ggZ8CZd3S6_zPoyRPDTJ4w.png

**Comment by nhooyr** [comment]
Don't put a space between the quotes.

**Comment by KikoPlayZ** [comment]
https://image.prntscr.com/image/WZbXqpNdTjaS1IPBv0CUlQ.png - still same

**Comment by KikoPlayZ** [comment]
sry for being annoying to you, I am newbie in this but already make this work

**Comment by nhooyr** [comment]
Sorry, I've got no idea then. I'm not familiar with windows. Your best bet is to keep googling around or ask someone familiar with the windows command line. You could also try using the linux on windows sub system.

**Comment by KikoPlayZ** [comment]
Ok thanks :) and thanks for making this amazing script, this is really useful

**Comment by KikoPlayZ** [comment]
Can use another command line like the git cmd or something like that? I am noob with this sorry :/

**Comment by nhooyr** [comment]
I wrote a quick Go program to do this for you so you wouldn't need to use a shell.

```go
package main

import (
	"os/exec"
	"io"
	"log"
	"os"
)

func main() {
	c := exec.Command("echo", "-email", "me@domain.com", "-pass", "secret", "-guild", "server", "-chan", "channel")
	cmdStdout, err := c.StdoutPipe()
	if err != nil {
		log.Fatal(err)
	}
	cmdStderr, err := c.StderrPipe()
	if err != nil {
		log.Fatal(err)
	}
	err = c.Start()
	go func() {
		_, err := io.Copy(os.Stdout, cmdStdout)
		if err != nil {
			log.Fatal(err)
		}
	}()
	_, err = io.Copy(os.Stderr, cmdStderr)
	if err != nil {
		log.Fatal(err)
	}
}
```

Just edit the details (pass, server etc) to fit what you need.

**Comment by nhooyr** [comment]
That should fix your problem so I'm gonna close this issue.

**Comment by KikoPlayZ** [comment]
Created a new issue: https://image.prntscr.com/image/qO_iBZKWTLenyMV7gSrl7g.png

**Comment by KikoPlayZ** [comment]
PS: Sorry for reopening

**Comment by nhooyr** [comment]
Oh, haha I missed a small detail. See where it says `"echo"` on the first line of the main function? Change that string to the path of the rankbot executable.

**Comment by KikoPlayZ** [comment]
c := exec.Command("go run C:\Users\-KikoGrilo\Desktop\rankbot-master\main.go", "-email", "kiko-grilo@hotmail.com", "-pass", "password", "-guild", "Eurovision Discord <3", "-chan", "bot_commands")

Like this?

**Comment by nhooyr** [comment]
No, first run `go build` inside of `C:\Users-KikoGrilo\Desktop\rankbot-master`. That will generate an executable. Then `c := exec.Command("C:\Users-KikoGrilo\Desktop\rankbot-master\rankbot-master", "-email", "kiko-grilo@hotmail.com", "-pass", "password", "-guild", "Eurovision Discord <3", "-chan", "bot_commands")`

**Comment by KikoPlayZ** [comment]
Like this?
![image](https://user-images.githubusercontent.com/30558038/28755006-855dec24-7549-11e7-9784-a50abfd730b6.png)

**Comment by KikoPlayZ** [comment]
not making it

**Comment by nhooyr** [comment]
Ok, forget all of this. Delete that file. I'll make it more simple.

Just edit the main.go in this repo. Change the following lines.

https://github.com/nhooyr/rankbot/blob/072e50b1a2e8407ba013981c05e97c4e9818a5d7/main.go#L11-L18

E.g.
```go
var (
	email    = "some email"
	pass     = "pass"
	guild    = "server"
	channel  = "channel"
	message  = "_"
	interval = 60
)
```

**Comment by nhooyr** [comment]
And then just `go run main.go`

**Comment by KikoPlayZ** [comment]
ok
in this case this?

var (
	email    = "kiko-grilo@hotmail.com/"
	pass     = "password"
	guild    = "Eurovision Discord <3"
	channel  = "bot_commands"
	message  = "_"
	interval = 60
)

**Comment by KikoPlayZ** [comment]
![image](https://user-images.githubusercontent.com/30558038/28755097-f2ee08a4-754a-11e7-8d2c-d7c253164f1b.png)

**Comment by nhooyr** [comment]
lol, I missed one more detail. Do the following instead

```go
var (
	email    = flag.String("email", "kiko-grilo@hotmail.com", "account email")
	pass     = flag.String("pass", "password", "account password")
	guild    = flag.String("guild", "Eurovision Discord <3", "guild (server) to join")
	channel  = flag.String("chan", "bot_channels", "channel to join")
	message  = flag.String("msg", "_", "message to be sent")
	interval = flag.Int64("int", 60, "interval between messages in seconds")
)
```

**Comment by KikoPlayZ** [comment]
IT WORKED! just saying thank you for your amazing support and thanks for being nice to me since I am a big amateur in this programming world :) 👍 to you!

**Comment by nhooyr** [comment]
Glad it worked out.

**Comment by KikoPlayZ** [comment]
Now you can close the thread 😂
